/**
 * @file birthdayCandles.cpp
 * @author Michelle Tran
 * @brief You are in charge of the cake for a child's birthday. You have decided the 
 *        cake will have one candle for each year of their total age. They will only be able 
 *        to blow out the tallest of the candles. Count how many candles are tallest.
 * @version 0.1
 * @date 2022-10-09
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#include <iostream>
#include <vector> 
#include <string> 
#include <fstream> 

using namespace std; 

int birthdayCakeCandles(vector<int> candles);

int main()
{
    ifstream inStream;
    // input.txt will hold all the candle sizes
    inStream.open("input.txt");
    // will hold all candle sizes
    vector<int> candles;

    // .eof -> end of file
    while(!inStream.eof())
    {
        int temp; 
        inStream >> temp;
        candles.push_back(temp);
        // ignore space made in the input.txt; 
        inStream.ignore(1,' '); 
    }

    int candleCount = birthdayCakeCandles(candles);

    cout << "You will be able to blow " << candleCount << " candles!"; 

    inStream.close();
    return 0; 
}

/**
 * ** This function description was generated by Mintlify Doc Writer for Python, JavaScript, TypeScript, C++, PHP, Java, C#, Ruby & more **
 * Find the largest number in the vector, then count how many of that number are in the vector.
 * 
 * @param candles an array of integers representing candle heights
 * 
 * @return The number of candles that are the largest size.
 */
int birthdayCakeCandles(vector<int> candles) {
    // find the largest candle size
    int largestNum(0); 
    for(int a : candles)
    {
        if(a > largestNum)
        {
            largestNum = a; 
        }
    }
    
    // count how many of the largest candles are there
    int counter(0); 
    for(int x : candles)
    {
        if(x == largestNum)
        {
            counter++; 
        }
    }
    
    return counter; 
}